augmentations:
  horizontal_flip: null
  random_crop: null
  resize: null
checkpoint:
  save_frequency: null
  save_path: null
data:
  aoi_path: ../emilia_aoi/training.shp
  init_args:
    means: null
    stds: null
  root_dir: null
  target_times: null
  test_split: null
  train_split: null
  val_split: null
logging:
  log_dir: null
  log_frequency: null
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    factor: 0.5
    monitor: val/loss
    patience: 5
model:
  device: cpu
  hidden_layers: null
  input_size: null
  model_path: null
  name: CNN-ConvLSTM
  output_size: 1
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
    weight_decay: 0.1
training:
  batch_size: 32
  epochs: 10
  identifier: vgd
  num_workers: 25
  usecase: displacement
